### ISSUE TITLE
Create settings page - disease information tab

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#104]
The disease information tab on the global settings page gives the md the possibility to configure the content that is shown in the disease wiki in the patient dashboard. Here the MD can also manage population recommendations for diseases.

Implement the disease information tab according to this mock up: 
https://www.figma.com/file/zT9fQNemx9QA9CDaigBM4y/MD-Dashboard-UI?node-id=25%3A497

**Comment by FuchsDominik** [comment]
Done in #93
