### ISSUE TITLE
Build authentication into redux store

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#18]
# Description 
The authentication and authorisation on the client side should be handled via the redux pattern. 

For a detailed tutorial on how to do this for orientation (the tutorial is already outdated again) check [here](https://jasonwatmore.com/post/2017/09/16/react-redux-user-registration-and-login-tutorial-example).

# Acceptance Criteria
- Redux actions are in place and working
- Redux store exists
- Secured routing works
- Reducers are working
- A userservice provides a corresponding API
- The authentication logic has been integrated into the corresponding UI from #17

**Comment by n-krueger** [comment]
Blocked by https://github.com/FHIR-Vaccination-Pass/vaccination-pass-server/issues/2
