### ISSUE TITLE
Security vulnerabilities due to downgrade to react 17.0.2

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#23]
To resolve peer dependencies of many of the libraries we use, we had to downgrade from react v18.0.0 to react v17.0.2 in #22 . The audit process reveals that this results in 19 new high security vulnerabilities. 

We need to discuss on how to resolve these.

**Comment by n-krueger** [comment]
We are blocked on this by our dependencies needing to support React 18. In the scope of the project I don't think we should spend time on this.
