### ISSUE TITLE
Create patient dashboard UI

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#25]
Create the patient dashboard view. This view is the main page for patients who are logged in. It should display the following:
 
- A widget with recommendations for vaccinations
- ~~A widget with reminders for appointments and vaccinations that need to be freshened up in the near future~~
- A list of all the vaccinations a patient received so far
- (optional) An info field with information about the current consulting practitioner (may be changing)
- A search bar where the patient can query for vaccination information appointments etc.

**Comment by ValiHar** [comment]
Also kann das Issue jetzt geclosed werden oder?

**Comment by n-krueger** [comment]
Yes
