### ISSUE TITLE
Create vaccination recommendation detail view

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#30]
Create a detail view for a vaccination recommendation that is accessible via the recommendation widget on the patient-dashboard. 

The detail view should include: 
- Information concerning the vaccine
- Date and Time recommendations for the vaccination
- ~~An interface to create an appointment based on the recommendation~~
- A button to discard the recommendation

**Comment by ValiHar** [comment]
BLOCKED: This issue is blocked by the development of our object model

**Comment by n-krueger** [comment]
The option to discard recommendations or to document contra-indications is better placed in the MD dashboard.

**Comment by ValiHar** [comment]
Including recommendation in the wiki details page, therefore a dedicated details page for the recommendations is not needed.
