### ISSUE TITLE
Preordering medicine

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#31]
In #30 we define a recommendation detail view that gives you the possibility to schedule an appointment with an MD to get one or multiple vaccine shots. 
Some vaccines are not very common and need to be ordered. Are we planning to include a feature where we can inform the MD about pre-ordering a specific vaccine for the patient?

**Comment by n-krueger** [comment]
I think this is out of scope for the project.
