### ISSUE TITLE
Create patient profile widget

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#35]
Create a patient profile widget that is included on the patient dashboard from #25. 

This widget is intended to show minimal user informations for the patient and should include the following:
- Patient profile picture, if present
- First, Last name
- Email-Address 
- Logout button
- Button to navigate to the patient details view #34

**Comment by n-krueger** [comment]
Considering that the patient dashboard is mobile-first, displaying the user profile picture in the top right and linking to https://github.com/FHIR-Vaccination-Pass/patient-dashboard/issues/34 when you click on it should be sufficient.
