### ISSUE TITLE
Improve Wiki page

### ISSUE THREAD

**Issue by FuchsDominik** [FHIR-Vaccination-Pass/patient-dashboard#40]
Improve the basic structure of the wiki page

**Comment by n-krueger** [comment]
Could you add a bit more information to the description on what needs to change/be enhanced. Especially how this relates to https://github.com/FHIR-Vaccination-Pass/patient-dashboard/issues/13

**Comment by n-krueger** [comment]
Ah sorry, you mean the Wiki about vaccinations in our application, right?

**Comment by ValiHar** [comment]
Yes we mean exactly that wiki :) going to specify it further.

**Comment by ValiHar** [comment]
Forgot to link PR, Issue already closed:
