### ISSUE TITLE
Fix sidebar responsiveness

### ISSUE THREAD

**Issue by FuchsDominik** [FHIR-Vaccination-Pass/patient-dashboard#46]
I noticed for thinner screens, the sidebar vanishes.

<img width="495" alt="Screenshot 2022-06-10 at 13 40 41" src="https://user-images.githubusercontent.com/44401560/173057655-c586e7a2-e098-4a9b-b2ff-4bf4dc3585fb.png">

**Comment by ValiHar** [comment]
That's actually a feature hahah 
It's called mobile responsiveness :P The menu appears when you click the user icon

**Comment by n-krueger** [comment]
We should discuss continuity of the design paradigms. E.g. a sidebar usually collapses to a drawer that can be extended with a button on the same side of the page as the sidebar was before.

**Comment by ValiHar** [comment]
But that's the case on desktop right now. You can collapse it, but it's simply not fully collapsing but rather to a minimal Icon bar. I think I do not understand where there is no continuity of design paradigms? Im going to wireframe everything now anyways, then we can discuss it properly next time :) (@n-krueger, @FuchsDominik )
