### ISSUE TITLE
e2e testing with cypress

### ISSUE THREAD

**Issue by ValiHar** [FHIR-Vaccination-Pass/patient-dashboard#8]
Hi @n-krueger @FuchsDominik @tklausen,
I was wondering if we want to stick to unit test in the React UIs for now or if we want to integrate e2e testing as well? 

If we integrate e2e testing I'd recommend [cypress.io](https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/) for this. 

What are your thoughts on this, please let me know! If we decide to integrate e2e testing, I'd create the corresponding issues and add a corresponding CI workflow to execute e2e tests.

**Comment by n-krueger** [comment]
IMO it is a bit early for e2e tests, we don't even have ends yet :)

I'd say we need the following:
- unit tests for logic
- storybook for component states

**Comment by ValiHar** [comment]
Feature postponed until MVP is finished.
